### ISSUE TITLE
"该指令和 set_by_lua 一样，在 Lua 脚本的后面不支持额外参数"翻译错了？

### ISSUE THREAD

**Issue by dengshiyong** [iresty/nginx-lua-module-zh-wiki#27]
章节：https://github.com/iresty/nginx-lua-module-zh-wiki#set_by_lua_block
其中“2.该指令和 set_by_lua 一样，在 Lua 脚本的后面不支持额外参数”中的“一样”，意思似乎应该是“不一样”？
linux下没法开QQ，只能这儿提意见啦。。。

**Comment by membphis** [comment]
这个翻译应该是没错的，您可以和原文对比一下。

https://github.com/openresty/lua-nginx-module#set_by_lua_block
1. this directive does not support extra arguments after the Lua script as in set_by_lua.
