### ISSUE TITLE
ngxexec章节的“例如，通过return ngx.redirect(...)，”应该是“例如，通过return ngx.exec(...)”？

### ISSUE THREAD

**Issue by dengshiyong** [iresty/nginx-lua-module-zh-wiki#28]
章节：https://github.com/iresty/nginx-lua-module-zh-wiki#ngxexec的“例如，通过return ngx.redirect(...)，”应该是“例如，通过return ngx.exec(...)”？

**Comment by membphis** [comment]
已经修正，非常感谢
