### ISSUE TITLE
ngxexit 的代码片段“ngx.exit(ngx.HTTP_OK)” 是不是应该为“ngx.exit(status)”？

### ISSUE THREAD

**Issue by dengshiyong** [iresty/nginx-lua-module-zh-wiki#29]
https://github.com/iresty/nginx-lua-module-zh-wiki#ngxexit 的代码片段
`ngx.status = ngx.HTTP_GONE
 ngx.say("This is our own content")
 -- 退出整个请求而不是当前处理阶段
 ngx.exit(ngx.HTTP_OK)`
中的“ngx.exit(ngx.HTTP_OK)”
是不是应该为“ngx.exit(status)”？

**Comment by membphis** [comment]
这里是对的。想要表达的是执行这条语句，就退出请求，并且应答码是 ngx.HTTP_OK 。
